1)
SELECT MAX(AGE) FROM PERSON

SELECT NAME FROM PERSON WHERE AGE = 39

SELECT NAME, AGE FROM PERSON WHERE AGE = (SELECT MAX(AGE) FROM PERSON)

--ERRO
--SELECT NAME, AGE FROM PERSON WHERE NAME = (SELECT MAX(AGE) FROM PERSON)



INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (21, 'Joice', 	'F', 40, 'MG', 'Pouso Alegre');
INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (22, 'Juvenal', 	'M', 28, 'MG', 'Estiva');

3)
SELECT NAME, AGE 
FROM PERSON 
WHERE AGE = (SELECT MAX(AGE) FROM PERSON WHERE GENDER = 'M') AND GENDER = 'M'

SELECT MAX(AGE) FROM PERSON WHERE GENDER = 'M'



4)
SELECT NAME, AGE 
FROM PERSON 
WHERE AGE = (SELECT MIN(AGE) FROM PERSON) AND GENDER = 'F'


SELECT NAME, AGE 
FROM PERSON 
ORDER BY AGE DESC

11)
SELECT MAX(AGE), CITY FROM PERSON GROUP BY CITY
--PRECISA DE ANINHADO PARA COMPARAR DOIS CAMPOS
--PRECISA DE ANINHAR COM JUNÇÃO
--CORRIGIR O ENUNCIADO DA QUESTÃO

12)
SELECT AVG(AGE), CITY FROM PERSON GROUP BY CITY HAVING AVG(AGE) < 35

13)
SELECT COUNT(*), CITY FROM PERSON GROUP BY CITY HAVING COUNT(*) > 2


14)
SELECT NAME, AGE FROM PERSON 
WHERE AGE = (SELECT MIN(AGE) FROM PERSON WHERE GENDER = 'M') AND GENDER = 'M'
UNION
SELECT NAME, AGE FROM PERSON 
WHERE AGE = (SELECT MIN(AGE) FROM PERSON WHERE GENDER = 'F') AND GENDER = 'F'

15)
SELECT AVG(AGE), CITY FROM PERSON GROUP BY CITY ORDER BY AVG(AGE) LIMIT 2 OFFSET 3

16)

SELECT MAX(AGE) FROM PERSON
SELECT NAME, 40-AGE FROM PERSON

SELECT NAME, (SELECT MAX(AGE) FROM PERSON)-AGE FROM PERSON

17)

--PRECISA DE ANINHAR COM JUNÇÃO
