CREATE TABLE PERSON (
  REGISTER NUMERIC NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  GENDER VARCHAR(1) NOT NULL,
  AGE NUMERIC NOT NULL,
  STATE VARCHAR(2) NOT NULL,
  CITY VARCHAR(50) NOT NULL
);

ALTER TABLE PERSON ADD CONSTRAINT PERSON_PK PRIMARY KEY (REGISTER);


INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (4, 'Joana', 	'F', 29, 'MG', 'Pouso Alegre');
INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (5, 'Júlia', 	'F', 30, 'SP', 'Osasco');
INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (6, 'Jane', 	'F', 30, 'RJ', 'Bota Fogo');
INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (7, 'Jeane', 	'F', 31, 'MG', 'Estiva');
INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (9, 'Josefina', 	'F', 33, 'SP', 'Guarulhos');
INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (11, 'Jenivânia', 	'F', 35, 'RJ', 'Niterói');
INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (14, 'Josie', 	'F', 38, 'MG', 'Pouso Alegre');
INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (20, 'Janine', 	'F', 39, 'SP', 'Guarulhos');

INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (1, 'José', 	'M', 29, 'RJ', 'Niterói');
INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (2, 'João', 	'M', 30, 'MG', 'Pouso Alegre');
INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (3, 'Jonas', 	'M', 31, 'SP', 'Osasco');
INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (8, 'Joaquim', 	'M', 32, 'RJ', 'Niterói');
INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (10, 'Jair', 	'M', 32, 'MG', 'Estiva');
INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (12, 'Jubileu', 	'M', 33, 'SP', 'Jundiaí');
INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (13, 'Jarbas', 	'M', 35, 'RJ', 'Bota Fogo');
INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (15, 'Jonathan', 	'M', 36, 'MG', 'Pouso Alegre');
INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (16, 'Jaime', 	'M', 37, 'SP', 'Guarulhos');
INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (17, 'Jailson', 	'M', 38, 'RJ', 'Bota Fogo');
INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (18, 'Jalison', 	'M', 39, 'MG', 'Pouso Alegre');
INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (19, 'Janderson', 	'M', 39, 'SP', 'Osasco');

INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (21, 'Joice', 	'F', 40, 'MG', 'Pouso Alegre');
INSERT INTO PERSON (REGISTER, NAME, GENDER, AGE, STATE, CITY) VALUES (22, 'Juvenal', 	'M', 28, 'MG', 'Estiva');
