CREATE TABLE DEPARTMENT (
	CODE INTEGER NOT NULL,
    NAME VARCHAR(30) NOT NULL
);
ALTER TABLE DEPARTMENT ADD CONSTRAINT DEP_PK PRIMARY KEY (CODE);

CREATE TABLE ROLE (
	CODE INTEGER NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    WAGE REAL NOT NULL--SALARIO
);
ALTER TABLE ROLE ADD CONSTRAINT ROL_PK PRIMARY KEY (CODE);

CREATE TABLE EMPLOYEE (
	REGISTRY INTEGER NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    DEPARTMENT_CODE INTEGER NOT NULL,
    ROLE_CODE INTEGER NOT NULL
);
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMP_PK PRIMARY KEY (REGISTRY);

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMP_DEP_FK FOREIGN KEY (DEPARTMENT_CODE)
													REFERENCES DEPARTMENT (CODE);

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMP_ROL_FK FOREIGN KEY (ROLE_CODE)
													REFERENCES ROLE(CODE);

