CREATE TABLE ACCOUNT
(
    OWNER_NAME VARCHAR(50) NOT NULL,
    ACCOUNT_NUMBER INTEGER NOT NULL,
    AMOUNT INTEGER NOT NULL
);

ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_pk PRIMARY KEY (OWNER_NAME);
