
CREATE TABLE CARGO (
	CODIGO SERIAL NOT NULL,
	NOME VARCHAR(20) NOT NULL
);

ALTER TABLE CARGO ADD CONSTRAINT CARGO_PK PRIMARY KEY (CODIGO);

CREATE TABLE FUNCIONARIO (
	CODIGO INTEGER NOT NULL, --usa sequence
	NOME VARCHAR(30) NOT NULL,
	ATIVO BOOLEAN NOT NULL,
	NASCIMENTO DATE NOT NULL,
	--INCLUINDO A FK
	CODIGO_CARGO INTEGER NOT NULL
);

ALTER TABLE FUNCIONARIO ADD CONSTRAINT FUN_PK PRIMARY KEY (CODIGO);

--INCLUINDO A FK
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FUN_FK FOREIGN KEY (CODIGO_CARGO) 
REFERENCES CARGO (CODIGO);

--CREATE TABLE DEPARTAMENTO (
--	CODIGO INTEGER NOT NULL, 
--	NOME VARCHAR(30) NOT NULL,
--	ATIVO BOOLEAN NOT NULL
--);

--ALTER TABLE DEPARTAMENTO ADD CONSTRAINT DEP_PK PRIMARY KEY (CODIGO);

CREATE SEQUENCE SEQ_FUNCIONARIO INCREMENT BY 1;
